### ISSUE TITLE
`copilot-theorem`: README mentions inexisting `Driver.hs`, `lightProver`

### ISSUE THREAD

**Issue by ivanperez-keera** [Copilot-Language/copilot#452]
**Description**

`copilot-theorem`'s README mentions a file `Driver.hs` that is not part of the library:
```
As an example, the following prover is used in Driver.hs:
```
and later
```
Some examples are in the examples folder. The Driver.hs contains the main function to run any example. 
```

It also says that there are two provers: one based on `Kind2`, and one called `lightProver`. The latter no longer exists, but we do have a `What4` module now.

These mentions should be adjusted or removed.

**Type**

- Bug: incorrect documentation.

**Additional context**

None.

**Requester**

- Max Fan (NASA)

**Method to check presence of bug**

Running a search through the tree brings up several mentions:
```
$ grep -nIHre 'Driver.hs'
copilot-theorem/README.md:205:As an example, the following prover is used in `Driver.hs`:
copilot-theorem/README.md:254:Some examples are in the *examples* folder. The `Driver.hs` contains the `main`
copilot-theorem/README.md:257:by changing one *import* directive in `Driver.hs`.
```

```
$ grep -nIHre 'lightProver'
copilot-theorem/README.md:79:prove (lightProver def) (check "gt0") spec
copilot-theorem/README.md:82:where `lightProver def` stands for the *light prover* with default
copilot-theorem/README.md:150:`lightProver :: Options -> Prover` function which builds a prover from a record
copilot-theorem/README.md:209:  lightProver def {onlyBmc = True, kTimeout = 5}
```

```
$ grep -nIHre '\<Light\>' | grep -ve 'XML'
copilot-theorem/README.md:71:  the `Copilot.Theorem.Light` and `Copilot.Theorem.Kind2` module.
copilot-theorem/README.md:123:Two provers are provided by default: `Light` and `Kind2`.
copilot-theorem/README.md:149:The *light prover* is defined in `Copilot.Theorem.Light`. This module exports the
copilot-theorem/README.md:399:#### The Light prover
copilot-theorem/README.md:402:basic *k-induction* algorithm [1]. The `Light` directory contains three files:
```

**Expected result**

The output of the above `grep` commands should be empty, indicating that that inexisting file/modules/functions are not mentioned.

**Desired result**

The output of the above `grep` commands should be empty, indicating that that inexisting file/modules/functions are not mentioned.

**Proposed solution**

The claims should be adjusted to match the existing file tree, modules and exports, either by updating the references to point to their current locations, or by removing the claims altogether.

**Further notes**

None.

**Comment by ivanperez-keera** [comment]
Change Manager: Confirmed that the README is outdated and mentions in-existing functions, modules and files.

**Comment by ivanperez-keera** [comment]
Technical Lead: Confirmed that the issue should be addressed.

**Comment by RyanGlScott** [comment]
I investigated these parts of `copilot-theorem` recently as well. I believe what the `README` refers to as `lightProver` has been superseded by the new `kInduction` prover, which is separate from the Kind2 and What4 provers. See also https://github.com/Copilot-Language/copilot/commit/976bc5f3c862bd36d67840741d675c0d208657d3, which removes `lightProver` in favor of `kInduction`.

**Comment by fdedden** [comment]
I have picked up fixing the README.

@RyanGlScott yes, it seems that `lightProver` has been superseded by `kInduction` (and the code has been refactored a bit since then). `copilot-theorem` is pretty much the only part of Copilot where I have nearly no knowledge about. What is the difference between `kInduction`:
https://github.com/Copilot-Language/copilot/blob/f8239019b9c83315a78e2a92221b862945aa3b7c/copilot-theorem/src/Copilot/Theorem/Prover/SMT.hs#L110-L116

and `kind2Prover`:
https://github.com/Copilot-Language/copilot/blob/f8239019b9c83315a78e2a92221b862945aa3b7c/copilot-theorem/src/Copilot/Theorem/Kind2/Prover.hs#L44-L49

Sounds like they solve the same problem with a different backend?

The README is rather outdated and incomplete, so maybe we just want to remove all parts mentioning `lightProver` and do a complete rewrite later on?

**Comment by RyanGlScott** [comment]
> Sounds like they solve the same problem with a different backend?

Yes, that is my understanding as well.

**Comment by fdedden** [comment]
Yeah, I think we may want to revisit and clean the library. @ivanperez-keera I propose we simply remove any obsolete information from the README, so that it is at least not plain incorrect about things. Later on we can investigate if `kInduction` and `kind2Prover` are actually equal, and deprecate one of them (in the end both are based on Yices). After this (and possibly other cleanup work) we can rewrite the README. What do you think?

**Comment by fdedden** [comment]
@ivanperez-keera I have made a branch (https://github.com/Copilot-Language/copilot/compare/master...fdedden:copilot:develop-fix-nonexisting-readme) that removes any mention to `Driver.hs` and the Light Prover. I have not tested the equivalence of the Light Prover with the k-induction prover yet, but it is a start. Let me know what you think.

BTW: I have seen numerous other typos and mistakes in the file, so it is in dire need of a cleanup.

**Comment by ivanperez-keera** [comment]
Technical Lead: Issue scheduled for fixing in Copilot 3.20.

Fix assigned to: @fdedden .

**Comment by fdedden** [comment]
Implementor: Solution implemented, review requested.

**Comment by ivanperez-keera** [comment]
Change Manager: Verified that:
- Solution is implemented:
  - [X] The code proposed compiles and passes all tests. Details:
    Build log: https://app.travis-ci.com/github/Copilot-Language/copilot/builds/270352630
  - [X] The solution proposed produces the expected result. Details:
    The change is to the README, so it's been evaluated by manual inspection. I checked some of the examples with kind2-0.7.2 to make sure they produce the expected results.
- [X] Implementation is documented. Details:
  The change is to the documetnation.
- [X] Change history is clear.
- [X] Commit messages are clear.
- [X] Changelogs are updated.
- [X] Examples are updated. Details:
   No updates needed.
- [X] Required version bumps are evaluated. Details:
  Bump not needed. Changes affect README only.

**Comment by ivanperez-keera** [comment]
Change Manager: Implementation ready to be merged.
